#!/bin/sh
ulimit -n 10032
echo 512 > /proc/sys/net/core/somaxconn
echo never > /sys/kernel/mm/transparent_hugepage/enabled
sysctl vm.overcommit_memory=1
su - redis -c '/usr/local/bin/redis-server /etc/redis/redis.conf'
